db.campaign.save({"id": 1, "parent_id": null, "name": 'Авто и Мото'});
db.campaign.save({"id": 2, "parent_id": 1, "name": 'Автострахование'});
db.campaign.save({"id": 3, "parent_id": 1, "name": 'Клубы автовладельцев'});
db.campaign.save({"id": 4, "parent_id": 1, "name": 'Мотоциклы'});
db.campaign.save({"id": 5, "parent_id": 1, "name": 'Оборудование и запчасти'});
db.campaign.save({"id": 6, "parent_id": 1, "name": 'Продажа / Покупка'});
db.campaign.save({"id": 7, "parent_id": 1, "name": 'Услуги'});
db.campaign.save({"id": 8, "parent_id": null, "name": 'Бизнес и Финансы'});
db.campaign.save({"id": 9, "parent_id": 8, "name": 'Бухгалтерия'});
db.campaign.save({"id": 10, "parent_id": 8, "name": 'Инвестиции'});
db.campaign.save({"id": 11, "parent_id": 8, "name": 'Кредиты'});
db.campaign.save({"id": 12, "parent_id": 8, "name": 'Право'});
db.campaign.save({"id": 13, "parent_id": 8, "name": 'Промышленность'});
db.campaign.save({"id": 14, "parent_id": 8, "name": 'Реклама, маркетинг и PR'});
db.campaign.save({"id": 15, "parent_id": 8, "name": 'Страхование'});
db.campaign.save({"id": 16, "parent_id": 8, "name": 'Телекоммуникации'});
db.campaign.save({"id": 17, "parent_id": null, "name": 'Недвижимость'});
db.campaign.save({"id": 18, "parent_id": 17, "name": 'Аренда'});
db.campaign.save({"id": 19, "parent_id": 17, "name": 'Дом, интерьер'});
db.campaign.save({"id": 20, "parent_id": 17, "name": 'Жилая недвижимость'});
db.campaign.save({"id": 21, "parent_id": 17, "name": 'Коммерческая недвижимость'});
db.campaign.save({"id": 22, "parent_id": 17, "name": 'Продажа / Покупка'});
db.campaign.save({"id": 23, "parent_id": 17, "name": 'Строительство и ремонт'});
db.campaign.save({"id": 24, "parent_id": null, "name": 'СМИ'});
db.campaign.save({"id": 25, "parent_id": 24, "name": 'Деловая пресса'});
db.campaign.save({"id": 26, "parent_id": 24, "name": 'Общеновостные ресурсы'});
db.campaign.save({"id": 27, "parent_id": 24, "name": 'Развлекательная пресса'});
db.campaign.save({"id": 28, "parent_id": null, "name": 'Женские ресурсы'});
db.campaign.save({"id": 29, "parent_id": 28, "name": 'Буду мамой!'});
db.campaign.save({"id": 30, "parent_id": 28, "name": 'Домашние питомцы'});
db.campaign.save({"id": 31, "parent_id": 28, "name": 'Красота и здоровье'});
db.campaign.save({"id": 32, "parent_id": 28, "name": 'Кулинария'});
db.campaign.save({"id": 33, "parent_id": 28, "name": 'Мода и стиль'});
db.campaign.save({"id": 34, "parent_id": 28, "name": 'Родители и дети'});
db.campaign.save({"id": 35, "parent_id": 28, "name": 'Садоводство'});
db.campaign.save({"id": 36, "parent_id": 28, "name": 'Свадьба и брак'});
db.campaign.save({"id": 37, "parent_id": null, "name": 'ЛайфСтайл'});
db.campaign.save({"id": 38, "parent_id": 37, "name": 'Афиша'});
db.campaign.save({"id": 39, "parent_id": 37, "name": 'Погода'});
db.campaign.save({"id": 40, "parent_id": 37, "name": 'Рестораны'});
db.campaign.save({"id": 41, "parent_id": 37, "name": 'Хобби и увлечения'});
db.campaign.save({"id": 42, "parent_id": 37, "name": 'Шоппинг'});
db.campaign.save({"id": 43, "parent_id": 37, "name": 'Я - фотограф!'});
db.campaign.save({"id": 44, "parent_id": null, "name": 'ХайТек'});
db.campaign.save({"id": 45, "parent_id": 44, "name": 'Аудио и Видео'});
db.campaign.save({"id": 46, "parent_id": 44, "name": 'Гаджеты'});
db.campaign.save({"id": 47, "parent_id": 44, "name": 'Железо'});
db.campaign.save({"id": 48, "parent_id": 44, "name": 'Компьютеры'});
db.campaign.save({"id": 49, "parent_id": 44, "name": 'Мир Apple'});
db.campaign.save({"id": 50, "parent_id": 44, "name": 'Мобильная связь'});
db.campaign.save({"id": 51, "parent_id": 44, "name": 'Техника'});
db.campaign.save({"id": 52, "parent_id": 44, "name": 'Фототехника'});
db.campaign.save({"id": 53, "parent_id": 44, "name": 'Электроника'});
db.campaign.save({"id": 54, "parent_id": null, "name": 'Спорт'});
db.campaign.save({"id": 55, "parent_id": 54, "name": 'Активный и экстремальный спорт'});
db.campaign.save({"id": 56, "parent_id": 54, "name": 'Новости спорта'});
db.campaign.save({"id": 57, "parent_id": 54, "name": 'Фан - клубы'});
db.campaign.save({"id": 58, "parent_id": 54, "name": 'Фитнес'});
db.campaign.save({"id": 59, "parent_id": 54, "name": 'Футбол!'});
db.campaign.save({"id": 60, "parent_id": 54, "name": 'Товары и услуги'});
db.campaign.save({"id": 61, "parent_id": null, "name": 'Путешествия'});
db.campaign.save({"id": 62, "parent_id": 61, "name": 'Страны'});
db.campaign.save({"id": 63, "parent_id": 61, "name": 'Советы бывалых, отзывы'});
db.campaign.save({"id": 64, "parent_id": 61, "name": 'Туры и отели'});
db.campaign.save({"id": 65, "parent_id": null, "name": 'Образование'});
db.campaign.save({"id": 66, "parent_id": 65, "name": 'Образовательные ресурсы'});
db.campaign.save({"id": 67, "parent_id": 65, "name": 'Рефераты, домашние задания'});
db.campaign.save({"id": 68, "parent_id": 65, "name": 'Словари, переводчики, справочники'});
db.campaign.save({"id": 69, "parent_id": null, "name": 'Отдых и развлечения'});
db.campaign.save({"id": 70, "parent_id": 70, "name": 'Видео'});
db.campaign.save({"id": 71, "parent_id": 70, "name": 'Игры'});
db.campaign.save({"id": 72, "parent_id": 70, "name": 'Кино'});
db.campaign.save({"id": 73, "parent_id": 70, "name": 'Музыка'});
db.campaign.save({"id": 74, "parent_id": 70, "name": 'Развлекательные новости'});
db.campaign.save({"id": 75, "parent_id": 70, "name": 'Фото'});
db.campaign.save({"id": 76, "parent_id": null, "name": 'Карьера'});
db.campaign.save({"id": 77, "parent_id": 76, "name": 'Вакансии'});
db.campaign.save({"id": 78, "parent_id": 76, "name": 'Резюме'});
db.campaign.save({"id": 79, "parent_id": 76, "name": 'Профессиональные сообщества и социальные сети'});
db.campaign.save({"id": 80, "parent_id": 76, "name": 'Фриланс'});
db.campaign.save({"id": 81, "parent_id": null, "name": 'Справочники и классификаторы'});
db.campaign.save({"id": 82, "parent_id": null, "name": 'Блоги, социальные сети, сообщества'});
db.campaign.save({"id": 83, "parent_id": null, "name": 'Разное'});
db.campaign.save({"id": 84, "parent_id": null, "name": 'Регионы'});
db.campaign.save({"id": 85, "parent_id": 1, "name": 'Тест-Драйв'});
db.campaign.save({"id": 86, "parent_id": 8, "name": 'Обзоры рынков'});
db.campaign.save({"id": 87, "parent_id": 84, "name": 'Все регионы'});    